version: '3'

services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: transaction_db
      POSTGRES_PASSWORD: 26538hsvgn8p
    ports:
      - "6543:5432"

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - psql
